blank_issues_enabled: false
contact_links:
  - name: Communauté Planète Casio
    url: https://www.planet-casio.com/Fr/forums/
    about: Questions générales sur la programmation des calculatrices Casio.
